# -*- mode: ruby -*-
# vi: set ft=ruby  :

Vagrant.configure("2") do |config|
	config.vm.define "ubuntu" do |ubuntu|
		ubuntu.vm.box = "ubuntu/focal64"
		ubuntu.vm.hostname = "ubuntu.marcelobreda.local"
		ubuntu.vm.network "public_network", bridge: "wlp6s0",ip: "192.168.0.58"
		ubuntu.vm.provider "virtualbox" do |vb|
			vb.name = "ubuntu"
			vb.memory = 2048
			vb.cpus = 2
		end
		ubuntu.vm.provision "shell", path:"./scripts/script.sh"
		
	end		
	
	
end
