# -*- mode: ruby -*-
# vi: set ft=ruby  :

Vagrant.configure("2") do |config|
	config.vm.define "rke" do |rke|
		rke.vm.box = "ubuntu/focal64"
		rke.vm.hostname = "rke.marcelobreda.local"
		rke.vm.network "public_network", bridge: "wlp6s0",ip: "192.168.0.60"
		rke.vm.provider "virtualbox" do |vb|
			vb.name = "rke"
			vb.memory = 2048
			vb.cpus = 2
		end
		rke.vm.provision "shell", path:"./scripts/script.sh"
		
	end		
	
	
end
